import dayjs from 'dayjs'
import { utils, writeFileXLSX } from 'xlsx'
import packageJson from '@/../package.json'

export default function aoaToXlsx(
    fileName: string,
    rows: AoaRows,
    header?: string[],
) {
    const generatedAt = ' — ' + dayjs().format('YYYY-MM-DD HH:mm:ss')
    const finalFileName = fileName + ' ' + generatedAt + '.xlsx'

    const workbook = utils.book_new()
    const worksheet = header
        ? utils.aoa_to_sheet([header, ...rows])
        : utils.aoa_to_sheet(rows)

    utils.book_append_sheet(workbook, worksheet)

    writeFileXLSX(workbook, finalFileName, {
        Props: {
            Author: process.env.NEXT_PUBLIC_APP_NAME,
            Comments: `Auto generated by ${process.env.NEXT_PUBLIC_APP_NAME} v${packageJson.version} at ${generatedAt}`,
            CreatedDate: new Date(),
        },
    })
}

export type AoaRows = (string | number | null)[][]
