import dayjs from 'dayjs'
import { utils, writeFileXLSX } from 'xlsx'
import packageJson from '@/../package.json'

export function aoaToXlsx(
    fileName: string,
    header: string[],
    body: (string | number | undefined)[][],
) {
    const generatedAt = dayjs().format('YYYY-MM-DD HH:mm:ss')
    const finalFileName = fileName + ' ' + generatedAt + '.xlsx'

    const workbook = utils.book_new()
    const worksheet = utils.aoa_to_sheet([header, ...body])
    utils.book_append_sheet(workbook, worksheet)

    writeFileXLSX(workbook, finalFileName, {
        Props: {
            Author: process.env.NEXT_PUBLIC_APP_NAME,
            Comments: `Auto generated by ${process.env.NEXT_PUBLIC_APP_NAME} v${packageJson.version} at ${generatedAt}`,
            CreatedDate: new Date(),
        },
    })
}
